# Generated by Django 3.1.3 on 2020-11-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa sport')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=128, verbose_name='Adres')),
                ('when', models.DateTimeField(verbose_name='Kiedy')),
                ('min_players', models.PositiveIntegerField(max_length=128)),
                ('max_players', models.PositiveIntegerField(max_length=128)),
                ('explevel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Level')),
                ('city', models.CharField(max_length=128, verbose_name='Miasto')),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sports.sport')),
            ],
        ),
    ]
