# Generated by Django 3.1.3 on 2020-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_players',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_players',
            field=models.PositiveIntegerField(),
        ),
    ]
