# Generated by Django 3.1.3 on 2020-11-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20201121_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='what',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sports.sport', verbose_name='Sport'),
        ),
    ]
